name: gym_db
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2
  http: 1.3.0
  mobile_scanner: ^6.0.7
  file_picker: ^10.1.0
  csv: ^5.0.2
  http_parser: ^4.1.2
  path_provider: ^2.0.15
  intl: ^0.20.2
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - config.env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
