name: gym_db
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

firebase_core: ^2.25.3
firebase_auth: ^4.17.6
firebase_storage: ^11.6.6
firebase_ui_auth: ^1.12.1
google_sign_in: ^6.1.5
